#!/usr/bin/env bash

GPUS=$1
CONFIG=$2
WORK_DIR=$3
LOAD_FROM=$4
# `metric.json` generated by `test_local.sh` or `flops.json` generated by `count_flops_local.sh`
MODEL_SPACE_PATH=$5
PORT=${PORT:-29500}

# CONFIG=configs/local_examples/fast_finetune/faster_rcnn_ar50to101_ft2e.py

python -m torch.distributed.launch \
    --nproc_per_node=$GPUS \
    --master_port=$PORT \
    "$(dirname $0)/../tools"/finetune_supernet.py \
    ${CONFIG} \
    --launcher pytorch \
    --work-dir ${WORK_DIR} \
    --eval bbox \
    --load-from ${LOAD_FROM} \
    --model-space-path ${MODEL_SPACE_PATH}

